name: generate-documentation
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run mode flag'
        required: false
        default: 'true'
jobs:
  generate-doc:
    name: Generates documentation and pushes it to S3 bucket
    runs-on: ubuntu-latest
    steps:
      - name: Run docker image to generate and push documentation
        id: generate-push-doc
        uses: dotcms/s3-doc-pusher@main
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          dry_run: ${{ github.event.inputs.dry_run }}

